Update SG_FPRINTF to work with gcc unicode
Before the fix running saga_cmd without arguments and without library
directory would yield:
e:n
afterwards:
error: no valid module library found in path [...]

this error started after the silent mode was introduced (11-1-2010)